sudo: required

services:
  - docker

install:
  - docker login --email=$DOCKER_HUB_EMAIL --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD

script:
  - cd alpine
  - docker build -t $DOCKER_IMAGE_NAME_ALPINE .
  - cd ../ubuntu
  - docker build -t $DOCKER_IMAGE_NAME_UBUNTU .

env:
  global:
    - DOCKER_IMAGE_NAME_ALPINE=i05nagai/sphinx-breathe:alpine-1.6.3
    - DOCKER_IMAGE_NAME_UBUNTU=i05nagai/sphinx-breathe:ubuntu-1.6.3
